import math
from fractions import Fraction

import pytest

from conftest import EXAMPLES_DIR, REPO_ROOT, stlsat_available
from parse_graph import Interval, Path, build_tree_from_dot, discover_all_variables, generate_signal_space_from_formula, standardize
from reference_semantics import parse
from similarity.canon import canonicalize, cell_key
from similarity.stl_similarity import (
    build_aligned_volumes,
    build_volume_from_paths,
    calc_similarity_from_formulas,
    compute_similarity,
    is_bounded,
    is_undefined,
    measure,
    merge_pieces,
    one_way_similarity,
    point_sim_d,
    resolve_D,
    signal_spaces_from_definition,
    trim_trailing_undef,
)


def volume_from_dot_fixture(dot_name):
    content = (EXAMPLES_DIR / dot_name).read_text(encoding="utf-8")
    root = build_tree_from_dot(content)
    all_vars = discover_all_variables(content)
    paths = standardize(root, all_vars)
    return build_volume_from_paths(dot_name, paths, all_vars)


def test_point_sim_d_matches_preliminaries_worked_example():
    # preliminaries.tex, Section AltPointSim: c1=[2,inf), c2=[5,inf).
    c1 = [Interval(2, math.inf)]
    c2 = [Interval(5, math.inf)]
    assert math.isclose(point_sim_d(c1, c2, 100), 95 / 98)
    assert math.isclose(point_sim_d(c1, c2, 10), 5 / 8)


def test_worked_example_matches_EXAMPLE_md():
    """The pair EXAMPLE.md walks through, end to end.

    EXAMPLE.md and figures/example/*.png are generated by plot_pipeline.py and
    quote these three numbers throughout. plot_pipeline.py checks its own
    arithmetic against the metric, but nothing stops the metric itself from
    moving and leaving the committed document describing a score the code no
    longer produces. This is that check.

    phi = G[0,1](x>0) && F[0,1](y<3)   theta = (x>0) U[0,1] (y<3)

    phi is strictly contained in theta: theta's u=0 disjunct discharges the
    until at instant 0 and leaves x@t1 free, while phi's G[0,1] requires x>0
    there regardless. So the forward direction is exact (every canonical cell
    of phi is also one of theta) and the backward one is not.
    """
    phi = "G[0,1](x>0) && F[0,1](y<3)"
    theta = "(x>0) U[0,1] (y<3)"
    paths1, paths2, all_vars = signal_spaces_from_definition(phi, theta)
    assert all_vars == ["x", "y"]

    D = resolve_D(None, parse(phi), parse(theta))
    assert D == 4                      # max|con(phi) u con(theta)| + 1 = 3 + 1

    volume1, volume2 = build_aligned_volumes(phi, paths1, theta, paths2,
                                             all_vars=all_vars)
    assert len(volume1.volume) == 3
    assert len(volume2.volume) == 5

    # The metric reports floats by design (point_sim_d calls float() at the
    # boundary), so these are the exact doubles the pipeline produces, not
    # rationals: 4.5/5 and 1.9/2 are both representable without rounding.
    forward = one_way_similarity(volume1, volume2, all_vars, D)
    backward = one_way_similarity(volume2, volume1, all_vars, D)
    assert forward == 1.0              # phi's cells are all present in theta's
    assert backward == 0.9             # theta0 and theta1 have no phi twin
    assert calc_similarity_from_formulas(phi, theta, D=D) == 0.95


def test_worked_example_part2_matches_EXAMPLE_md():
    """EXAMPLE.md Part 2: bounded atoms, a disjunction, four paths.

    phi = F[0,1]((x>0 && x<2) || (x>4 && x<6))   theta = F[0,1](x>1 && x<5)

    This is the pair that exercises point_sim_d's Jaccard branch. Part 1's pair
    reaches it on no call at all -- every one of its slabs is a half-line, so
    every comparison exits at the identical-after-truncation or disjoint early
    return. Here the two breakpoint sets are disjoint ({0,2,4,6} vs {1,5}), so
    no slab of one equals a slab of the other and the ratio is the whole story.
    """
    phi = "F[0,1]((x>0 && x<2) || (x>4 && x<6))"
    theta = "F[0,1](x>1 && x<5)"
    paths1, paths2, all_vars = signal_spaces_from_definition(phi, theta)
    assert all_vars == ["x"]
    assert (len(paths1), len(paths2)) == (4, 2)   # 2 disjuncts x 2 witness instants

    D = resolve_D(None, parse(phi), parse(theta))
    assert D == 7                                 # max|con| + 1 = 6 + 1

    volume1, volume2 = build_aligned_volumes(phi, paths1, theta, paths2,
                                             all_vars=all_vars)
    assert (len(volume1.volume), len(volume2.volume)) == (16, 5)

    # The Jaccard branch itself, on the slab pair EXAMPLE.md derives by hand:
    # meet (1,2) has length 1, join (0,5) has length 5.
    assert point_sim_d([Interval(0, 2, True, True)],
                       [Interval(1, 5, True, True)], 7) == 1 / 5

    # A bounded slab pair is D-invariant -- it lies inside every legal window --
    # while the unbounded pairs in the same table drift towards 1 as D grows.
    # That contrast is the point of Part 2's "Why D matters" table.
    assert point_sim_d([Interval(0, 2, True, True)],
                       [Interval(1, 5, True, True)], 100) == 1 / 5

    score = calc_similarity_from_formulas(phi, theta, D=D)
    assert math.isclose(score, 0.4159375)         # NOT equal: 0.41593749999999996


def test_worked_example_part3_matches_EXAMPLE_md():
    """EXAMPLE.md Part 3: the L-shape, cut two ways, from real formula strings.

    tests/test_canon.py pins the same region, but builds it as hand-made boxes
    and never goes near the parser -- its L_SHAPE_1/L_SHAPE_2 constants use
    chained comparisons ("0<=x<=2") and are display labels, not input. This one
    drives the region from STL that actually parses, which is what EXAMPLE.md
    shows, so a fragment change that broke the document would fail here.

    The claim is stronger than "scores 1.0": the two decompositions share no
    box, yet canonicalise to the identical cell SET.
    """
    phi = "((x>=0 && x<=2) && (y>=0 && y<=1)) || ((x>=0 && x<=1) && (y>=1 && y<=2))"
    theta = "((x>=0 && x<=1) && (y>=0 && y<=2)) || ((x>=1 && x<=2) && (y>=0 && y<=1))"
    paths1, paths2, all_vars = signal_spaces_from_definition(phi, theta)
    assert all_vars == ["x", "y"]
    assert (len(paths1), len(paths2)) == (2, 2)

    cells1, cells2 = canonicalize(paths1), canonicalize(paths2)
    assert len(cells1) == len(cells2) == 3
    assert {cell_key(c) for c in cells1} == {cell_key(c) for c in cells2}

    D = resolve_D(None, parse(phi), parse(theta))
    before = compute_similarity(build_volume_from_paths(phi, paths1, all_vars),
                                build_volume_from_paths(theta, paths2, all_vars), D=D)
    assert before == 0.75                         # box-to-box, no canonicalisation
    assert calc_similarity_from_formulas(phi, theta, D=D) == 1.0


def test_point_sim_d_undefined_cases():
    undef = [Interval(-math.inf, math.inf)]
    defined = [Interval(0, 5)]
    assert point_sim_d(undef, undef, 100) == 1.0
    assert point_sim_d(undef, defined, 100) == 0.0
    assert point_sim_d(defined, undef, 100) == 0.0


def test_point_sim_d_disjoint_is_zero():
    a = [Interval(0, 1)]
    b = [Interval(2, 3)]
    assert point_sim_d(a, b, 100) == 0.0


def test_point_sim_d_identical_bounded_is_one():
    a = [Interval(0, 5)]
    assert point_sim_d(a, a, 100) == 1.0


def test_is_undefined_and_is_bounded():
    assert is_undefined([Interval(-math.inf, math.inf)])
    assert not is_bounded([Interval(-math.inf, math.inf)])
    assert not is_undefined([Interval(0, 5)])
    assert is_bounded([Interval(0, 5)])
    assert not is_bounded([Interval(0, math.inf)])


def test_merge_pieces_collapses_duplicates():
    pieces = [Interval(0, math.inf), Interval(0, math.inf)]
    merged = merge_pieces(pieces)
    assert len(merged) == 1
    assert merged[0].to_tuple() == (0.0, math.inf, False, True)


def test_measure_ignores_duplicate_overlap():
    # a naive sum-of-lengths would double-count this to 6, the correct
    # measure of the union [2,5] is 3.
    pieces = [Interval(2, 5), Interval(2, 5)]
    assert measure(pieces) == 3.0


def test_measure_is_infinite_for_unbounded_piece():
    assert measure([Interval(0, math.inf)]) == math.inf


def test_self_similarity_is_exactly_one():
    # preliminaries.tex "Soundness demonstration": S(phi)=S(theta) => G=1.
    # Comparing a formula's signal space against itself is the sharpest
    # instance of that (phi == theta), checked against real code.
    for dot_name in ("graph_G.dot", "graph_F_gex.dot", "graph_G_or.dot", "graph_F_g_or_eqx.dot"):
        volume = volume_from_dot_fixture(dot_name)
        assert compute_similarity(volume, volume) == 1.0


def test_trim_trailing_undef_drops_trailing_silence_only():
    # A path that discharges its obligation at t=0 and is free afterwards --
    # only the trailing undef run should be dropped.
    path = Path({
        0: {"x": [Interval(0, math.inf)]},
        1: {"x": [Interval(-math.inf, math.inf)]},
        2: {"x": [Interval(-math.inf, math.inf)]},
    })
    trimmed = trim_trailing_undef(path)
    assert sorted(trimmed.timeline.keys()) == [0]


def test_trim_trailing_undef_leaves_leading_and_real_content_alone():
    # Leading undef (not yet triggered) and any real content are untouched --
    # only a trailing all-undef run is dropped.
    path = Path({
        0: {"x": [Interval(-math.inf, math.inf)]},
        1: {"x": [Interval(0, math.inf)]},
        2: {"x": [Interval(-math.inf, math.inf)]},
    })
    trimmed = trim_trailing_undef(path)
    assert sorted(trimmed.timeline.keys()) == [0, 1]


def test_trim_trailing_undef_noop_when_no_trailing_silence():
    path = Path({0: {"x": [Interval(0, math.inf)]}, 1: {"x": [Interval(0, math.inf)]}})
    trimmed = trim_trailing_undef(path)
    assert sorted(trimmed.timeline.keys()) == [0, 1]


def test_trim_trailing_undef_fully_silent_path_collapses_to_empty():
    path = Path({0: {"x": [Interval(-math.inf, math.inf)]}, 1: {"x": [Interval(-math.inf, math.inf)]}})
    trimmed = trim_trailing_undef(path)
    assert trimmed.timeline == {}


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_disjoint_time_windows_score_zero_not_spuriously_positive():
    # The reported bug: F[3,4] and F[0,2] are never obligated at the same
    # instant. Both formulas' genuine "already discharged" / "not yet started"
    # silence at the shared instants (t=1,2) used to score as agreement
    # (undef == undef), inflating this to ~0.3-0.45.
    #
    # The silence also must not be sliced into a concrete half-interval that
    # could coincidentally match the other formula's real constraint:
    # F[3,4]'s tableau never constrains x before t=3 (undef, not "x<0"), and
    # canonicalize() only ever cuts an axis at breakpoints the formula's *own*
    # boxes contribute -- see similarity/canon.py's _breakpoints.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas(
        "F[3,4] x>0", "F[0,2] x>0", tabex_root=REPO_ROOT) == 0.0


def test_point_sim_d_identical_degenerate_interval_is_one():
    # preliminaries.tex, Definition AltPointSim: two identical degenerate
    # constraints (e.g. from an atom x==5) must score 1, not fall through to
    # the Jaccard case as 0/0 (zero-length intersection).
    c = [Interval(5, 5)]
    assert point_sim_d(c, c, 100) == 1.0


def test_one_way_similarity_unsat_vs_sat_is_zero_not_one():
    # Eq. 7: exactly one of P(phi), P(theta) empty -> 0 (maximally
    # dissimilar), not 1. Also must not crash computing the reverse
    # direction (max() over an empty path list).
    from similarity.stl_similarity import one_way_similarity

    unsat = build_volume_from_paths("unsat", [])
    sat_paths = [Path({0: {"x": [Interval(0, math.inf)]}})]
    sat = build_volume_from_paths("sat", sat_paths, all_vars=["x"])

    assert one_way_similarity(unsat, sat, ["x"], 100) == 0.0
    assert one_way_similarity(sat, unsat, ["x"], 100) == 0.0
    assert compute_similarity(unsat, sat) == 0.0


def test_one_way_similarity_both_unsat_is_one():
    unsat1 = build_volume_from_paths("unsat1", [])
    unsat2 = build_volume_from_paths("unsat2", [])
    assert compute_similarity(unsat1, unsat2) == 1.0


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_tautological_disjunction_scores_one_end_to_end():
    # preliminaries.tex, Definition 7 / Remark 1: phi:=T, theta:=(x<=0)||(x>=0)
    # are equivalent (S(phi)=S(theta)=R). Handled by coarsening rather than
    # by cutting: theta's breakpoint at x=0 is not a bend of the region, so
    # canonicalize() drops it and theta's two cells merge into the single
    # unconstrained cell phi already had. phi is never refined up to theta --
    # see similarity/canon.py's _axis_partition.
    #
    # test_canon.py builds the same region by hand and compares cell sets;
    # this one is the end-to-end path, through a real tableau.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas("true", "(x<=0) || (x>=0)", tabex_root=REPO_ROOT) == 1.0


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_negated_bounds_are_equivalent_to_plain_bounds():
    # !(x<0) && !(x>10) is the same region as x>=0 && x<=10. Scored 0.0 before
    # canonical_atoms() learned to flip a negated atom's operator: stlsat's
    # "(!x < 0)" label matched no atom pattern, so the constraint was dropped
    # and the formula extracted as fully unconstrained.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas(
        "x>=0 && x<=10", "!(x<0) && !(x>10)", tabex_root=REPO_ROOT) == 1.0


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
@pytest.mark.parametrize("formula,rewritten,why", [
    ("y<-1", "(y<-1) && ((y>0) || (y<=0))",
     "dead disjunct: y<-1 && y>0 is a branch stlsat emits but rejects"),
    ("x==5", "(x==5) && ((y<=0) || (y>=0))",
     "tautological conjunct over a DEGENERATE region: x==5 is a point, and "
     "coarsening away the tautology's split must not erase it"),
    ("F[0,0](x<=2)", "(F[0,0](x<=2)) || ((F[0,0](x<=2)) && (x>0))",
     "absorption: the && conjunct must intersect, not union, into the slot"),
    ("((x<=2 || y<0) && x>=2)", "(((x<=2 || y<0) && x>=2)) || (((x<=2 || y<0) && x>=2))",
     "idempotence: merging branches on x must not drop their disagreement on y"),
    ("F[0,1]((x>1 && x<0))", "(F[0,1]((x>1 && x<0))) && ((y>0) || (y<=0))",
     "unsatisfiable both sides: stlsat's graph still holds the surviving tautology"),
    ("F[0,1]((x>0 && y>0) || (x<0 && y<0))",
     "(F[0,1](x>0 && y>0)) || (F[0,1](x<0 && y<0))",
     "two witness boxes: negating a pooled per-variable bucket kills both continuations"),
    ("((y<0) U[1,1] (x>0))", "(((y<0) U[1,1] (x>0))) && ((y>0) || (y<=0))",
     "closed-only intervals: the dead y<0 && y>0 branch survives as the point [0,0]"),
    ("(x<1) || (x>1)", "!(x==1)",
     "a hole at a breakpoint is a genuine bend, not a coarsenable split"),
    ("F[0,1](F[0,1](((x>-2 || y<-2) && (x<=-2 || y>=-2))))",
     "F[0,2](((x>-2 || y<-2) && (x<=-2 || y>=-2)))",
     "nested F over an XOR body: the witness disjunction must distribute"),
])
def test_equivalence_preserving_rewrites_score_one(formula, rewritten, why):
    # Minimal counterexamples from the randomised equivalence sweep
    # (verify_equivalence.py). Each scored below 1.0 before its fix in
    # parse_graph.py; `why` names the specific extraction bug.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas(formula, rewritten, tabex_root=REPO_ROOT) == 1.0, why


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_nested_G_in_F_equivalent_to_unfolded_conjunction():
    # F[0,1](G[0,1] x>0) and F[0,1](x>0 && G[1,1] x>0) both reduce to
    # (x(0)>0 && x(1)>0) || (x(1)>0 && x(2)>0). Scored 0.611 before O-marked
    # deferred obligations stopped leaking their inner conjuncts into the
    # continuation branch's own instant.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas(
        "F[0,1](G[0,1](x>0))", "F[0,1](x>0 && G[1,1](x>0))", tabex_root=REPO_ROOT) == 1.0


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_unsatisfiable_formula_extracts_to_no_paths_without_a_sat_verdict():
    # stlsat stops expanding a branch once it knows the branch is dead, so its
    # DOT keeps childless nodes that were never COMPLETED -- here a leaf whose
    # only formula is still "F[0,1] (x > 1 && x < 0)". Read as an accepted
    # branch it becomes a fully unconstrained path and this unsatisfiable
    # formula comes out with a non-empty signal space.
    from parse_graph import generate_signal_space_from_formula

    paths = generate_signal_space_from_formula(
        "F[0,1]((x>1) && (x<0)) && ((y>0) || (y<=0))", tabex_root=REPO_ROOT)
    assert paths == []


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_disjunct_order_does_not_change_the_region():
    # These two differ only in the order of a disjunction, so they must extract
    # the same region. The shape is worth pinning: it used to make
    # tableau_loop() answer UNSAT for the first and SAT for the second, on
    # identical tableaux, because a later unsatisfiable sibling overwrote a
    # branch already found satisfiable. The extraction never reads that verdict
    # -- prune_incomplete() derives emptiness from the graph -- so this held
    # even while stlsat got it wrong, and it must keep holding.
    from parse_graph import generate_signal_space_from_formula
    from similarity.stl_similarity import calc_similarity_from_formulas

    formula = "(x<1) && ((F[2,3](y<2)) || (x>=1))"
    swapped = "(x<1) && ((x>=1) || (F[2,3](y<2)))"
    assert generate_signal_space_from_formula(formula, tabex_root=REPO_ROOT) != []
    assert calc_similarity_from_formulas(formula, swapped, tabex_root=REPO_ROOT) == 1.0


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_nested_G_collapse_over_a_dead_disjunct():
    # G[0,1](G[0,1] P) == G[0,2] P. Here P = (y<=-3 || x>=3) && x<-2, whose
    # second disjunct is dead against x<-2. That shape used to make stlsat
    # answer UNSAT for both sides (both are satisfiable, e.g. x=-3, y=-4) and,
    # having "decided", stop expanding -- leaving a branch that still owed
    # "G[0,1] G[0,1] P", which standardize() then dropped rather than extract a
    # partial constraint from an unfinished node. It needs stlsat to unroll the
    # whole tableau, which is what m_stlsat's graph-output mode now does.
    from similarity.stl_similarity import calc_similarity_from_formulas

    body = "((y<=-3 || x>=3) && x<-2)"
    assert calc_similarity_from_formulas(
        f"G[0,1](G[0,1]{body})", f"G[0,2]{body}", tabex_root=REPO_ROOT) == 1.0


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
def test_a_truncated_branch_is_dropped_not_partially_extracted():
    # The invariant the above rests on: in a fully unrolled tableau every leaf
    # carries atoms only (graph_G.dot ends at "x > 0", graph_U.dot at
    # "x > 0, y > 3"), so a leaf still naming F/G/U is a branch stlsat stopped
    # expanding. Extracting from it would silently under-constrain the region.
    from parse_graph import build_tree_from_dot, prune_incomplete
    from conftest import EXAMPLES_DIR

    for name in ("graph_G.dot", "graph_U.dot", "graph_F_gex.dot"):
        tree = build_tree_from_dot((EXAMPLES_DIR / name).read_text(encoding="utf-8"))
        assert not prune_incomplete(tree), f"{name} is complete; nothing may be pruned"


@pytest.mark.integration
@pytest.mark.skipif(not stlsat_available(), reason="cargo/z3 not available")
@pytest.mark.parametrize("original,rewritten,why", [
    ("((x>0) U[0,0] (y>3))", "((x>0) && (y>3))",
     "U[0,0] pins the invariant AT the witness: it is not just the witness"),
    ("((x>0) U[2,2] (y>3))", "(G[0,2](x>0)) && (G[2,2](y>3))",
     "a point until is the invariant up to the witness, and the witness"),
    ("((x>0) U[0,2] (y>3))", "((x>0) U[0,2] ((x>0) && (y>3)))",
     "the invariant is already required at the witness, so conjoining it is a no-op"),
    ("((x>0) U[0,2] ((y>3) || (y<-3)))",
     "(((x>0) U[0,2] (y>3))) || (((x>0) U[0,2] (y<-3)))",
     "until distributes over a disjunction in its right argument"),
    ("(((y>0) || (y<=0)) U[1,3] (x>0))", "F[1,3](x>0)",
     "a vacuous invariant collapses until to eventually"),
])
def test_until_semantics(original, rewritten, why):
    # stlsat rewrites "phi U[a,b] psi" into "G[0,a] phi && (phi U[a,b] (phi && psi))",
    # so its until requires the invariant up to AND INCLUDING the witness --
    # NOT the textbook half-open [t, witness). Every case here is false under
    # the half-open reading, so this is the file to look at if a future stlsat
    # changes that rewrite.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas(original, rewritten, tabex_root=REPO_ROOT) == 1.0, why


# --------------------------------------------------------------------------
# D: the domain of Definition 2, a user parameter with a well-formedness bound
# --------------------------------------------------------------------------

def test_constants_collects_con_of_the_formula():
    # con(phi): every constant an atom compares against, exactly, across every
    # connective -- this is what the D bound is taken over.
    from reference_semantics import constants, parse

    formula = "(x>1 && y<=2) -> F[0,2](z==3 || (w>4 U[0,1] v!=5))"
    assert constants(parse(formula)) == {Fraction(n) for n in (1, 2, 3, 4, 5)}


def test_constants_of_true_and_false_is_empty():
    # true/false denote the whole space and the empty one; neither has a
    # finite boundary to bound D with.
    from reference_semantics import constants, parse

    assert constants(parse("true")) == set()
    assert constants(parse("false")) == set()


def test_constants_are_exact_rationals():
    # A constant rounded here would understate the D it is used to derive.
    from reference_semantics import constants, parse

    assert constants(parse("x>1/3")) == {Fraction(1, 3)}


def test_resolve_D_derives_one_above_the_largest_constant():
    from reference_semantics import parse

    assert resolve_D(None, parse("x>2"), parse("x>5")) == 6
    assert resolve_D(None, parse("x>-7"), parse("x<3")) == 8      # |−7| is the bound
    assert resolve_D(None, parse("true"), parse("false")) == 1    # no constants at all
    assert resolve_D(None, parse("x>1/3"), parse("x<2/7")) == Fraction(4, 3)


def test_resolve_D_refuses_a_D_at_or_below_the_bound():
    # Definition 2's condition is strict, so D == bound is out too.
    from reference_semantics import parse

    phi, theta = parse("x>2"), parse("x>5")
    for bad in (5, 3, Fraction(9, 2)):
        with pytest.raises(ValueError, match="not well formed"):
            resolve_D(bad, phi, theta)
    assert resolve_D(Fraction(11, 2), phi, theta) == Fraction(11, 2)


def test_resolve_D_refuses_a_non_positive_D():
    from reference_semantics import parse

    for bad in (0, -1):
        with pytest.raises(ValueError, match="must be positive"):
            resolve_D(bad, parse("x>2"), parse("x>5"))


def test_resolve_D_keeps_a_user_D_exact():
    from reference_semantics import parse

    D = resolve_D(10.5, parse("x>2"), parse("x>5"))
    assert D == Fraction(21, 2) and isinstance(D, Fraction)


def test_derived_D_uses_con_not_the_canonical_endpoints():
    # "(x<=100)||(x>=100)" is equivalent to `true`, so its canonical form
    # carries no finite endpoint and an endpoint-derived bound would return 6
    # here -- below the 100 Definition 2 demands. Guards against the formula
    # path going back to default_D().
    from reference_semantics import parse

    assert resolve_D(None, parse("(x<=100)||(x>=100)"), parse("x>0 && x<5")) == 101


def test_point_sim_d_with_a_rational_D_is_exact():
    # D = 21/2: intersection (5, 21/2] = 11/2, union (2, 21/2] = 17/2.
    c1, c2 = [Interval(2, math.inf)], [Interval(5, math.inf)]
    assert point_sim_d(c1, c2, Fraction(21, 2)) == float(Fraction(11, 17))


def test_user_D_reaches_the_score():
    # The paper's own Section 5.2 worked example, end to end from formulas.
    from similarity.stl_similarity import calc_similarity_from_formulas

    assert calc_similarity_from_formulas("x>2", "x>5", D=100) == 95 / 98
    assert calc_similarity_from_formulas("x>2", "x>5", D=10) == 5 / 8


def test_ill_formed_user_D_is_refused_end_to_end():
    from similarity.stl_similarity import calc_similarity_from_formulas

    with pytest.raises(ValueError, match="must exceed 5"):
        calc_similarity_from_formulas("x>2", "x>5", D=3)
